### PR TITLE
Adding encoding/decoding for ASCII

### PR DESCRIPTION
**Pull request by unguest**
I added a context menu option for ASCII 🚀 !

### CODE REVIEW

**Comment by unguest** [comment]
I don't understand why the test isn't passing... those are just space-based things => shouldn't they be considered as warnings ?
(I tested it, it works perfectly)

**Comment by Shankhanil** [comment]
I shall take a look ASAP @unguest

**Comment by unguest** [comment]
Oh ok thank you !

**Comment by unguest** [comment]
YOOHOOO => I've just undertand why it didn't works...

If you have any review / changes to submit me, I'm taking !

**Comment by nadchif** [comment]
Great job @unguest. Thank you once again

**Comment by unguest** [comment]
No problem !

BTW, is there any encoder 'needed' or let's say more important to implement ?

**Comment by nadchif** [comment]
> No problem !
> 
> BTW, is there any encoder 'needed' or let's say more important to implement ?

Yes, but we are still discussing and trying to work things out. Your input is welcome and valuable: https://ossenthusiasts.slack.com/archives/C01391X0B4K

**Comment by unguest** [comment]
Oh nice I'm joining !

**Comment by unguest** [comment]
@nadchif I need you to invite me to check the link you mention. Accoring you are using Slack, you may use the following email address : unguestdev@gmail.com

**Pull request merged**
